// Generated by /Users/tm/workspaces/bin/sync-security.py - DO NOT EDIT MANUALLY.
// Source: /Users/tm/workspaces/teams/dev-team/security/templates/robots.ts
// Profile: internal-only

import type { MetadataRoute } from "next";

// AI crawler bots - blokovat plosne na app/* a internal cestach.
// Na verejnem marketingu zalezi na profilu (viz sync-security.py).
const AI_CRAWLERS = [
  "GPTBot",
  "ChatGPT-User",
  "ClaudeBot",
  "Claude-Web",
  "anthropic-ai",
  "CCBot",
  "Google-Extended",
  "PerplexityBot",
  "Bytespider",
  "ImagesiftBot",
  "Omgilibot",
  "FacebookBot",
  "Diffbot",
  "Applebot-Extended",
  "Meta-ExternalAgent",
  "cohere-ai",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // Default: vsechny bots
      {
        userAgent: "*",
        disallow: ["/api/", "/dashboard/", "/portal/", "/admin/", "/x-honeypot-internal/"],
        allow: "/",
      },
      // {
        userAgent: AI_CRAWLERS,
        disallow: "/",
      },
      {
        userAgent: "*",
        disallow: "/",
      },
    ],
    sitemap: "https://theridion.qawave.ai/sitemap.xml",
    host: "https://theridion.qawave.ai",
  };
}

// Exportujeme list bots pro referenci v jinych mistech.
export { AI_CRAWLERS };
