"""WS-Security MVP test suite.

Covers:
  - UsernameToken PasswordText + PasswordDigest (hash format, nonce, created)
  - Timestamp only (Created + Expires present)
  - BinarySecurityToken (cert embed)
  - XML Signature via MemorySignature (build_zeep_wsse_plugin)
  - XML Signature via Signature file path (build_zeep_wsse_plugin)
  - Envelope injection (inject into existing header, create header if missing)
  - Path traversal guard (key_file_path outside allowed dirs)
  - Invalid cert raises clear error
  - /api/soap/ws-security/execute with malformed XML → 422
  - /api/soap/execute with wsse UsernameToken field (schema round-trip)
  - Algorithm constants: RSA-SHA256, RSA-SHA1
  - _TimestampPlugin.apply produces lxml Timestamp element
"""

from __future__ import annotations

import base64
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from theridion_sidecar.api.ws_security import (
    SOAP,
    WSSE,
    WSU,
    WsSecurityConfig,
    _safe_resolve_path,
    _TimestampPlugin,
    build_security_header,
    build_zeep_wsse_plugin,
    inject_security,
)

# Paths to test fixtures (self-signed cert generated by conftest or script)
FIXTURES = Path(__file__).parent / "fixtures"
KEY_FILE = FIXTURES / "test.key"
CERT_FILE = FIXTURES / "test.crt"


@pytest.fixture(scope="module")
def key_pem() -> str:
    return KEY_FILE.read_text()


@pytest.fixture(scope="module")
def cert_pem() -> str:
    return CERT_FILE.read_text()


SAMPLE_ENVELOPE = (
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">'
    "<soap:Header/>"
    "<soap:Body><TestOp><x>1</x></TestOp></soap:Body>"
    "</soap:Envelope>"
)

ENVELOPE_NO_HEADER = (
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">'
    "<soap:Body><Ping/></soap:Body>"
    "</soap:Envelope>"
)


@pytest.fixture()
def client(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> TestClient:
    monkeypatch.setenv("THERIDION_HOME", str(tmp_path))
    from theridion_sidecar.main import create_app

    return TestClient(create_app())


# ---------------------------------------------------------------------------
# UsernameToken tests
# ---------------------------------------------------------------------------


def test_username_token_text_contains_username_and_plaintext_password() -> None:
    cfg = WsSecurityConfig(
        type="UsernameToken",
        username="alice",
        password="secret",
        password_type="PasswordText",
        add_nonce=True,
        add_created=True,
        add_timestamp=False,
    )
    sec = build_security_header(cfg)
    xml_str = ET.tostring(sec, encoding="unicode")
    assert "alice" in xml_str
    assert "secret" in xml_str
    assert "PasswordText" in xml_str
    assert "Nonce" in xml_str
    assert "Created" in xml_str


def test_username_token_digest_password_is_not_plaintext() -> None:
    cfg = WsSecurityConfig(
        type="UsernameToken",
        username="bob",
        password="pass123",
        password_type="PasswordDigest",
        add_nonce=True,
        add_created=True,
        add_timestamp=False,
    )
    sec = build_security_header(cfg)
    xml_str = ET.tostring(sec, encoding="unicode")
    assert "bob" in xml_str
    assert "PasswordDigest" in xml_str
    # Password MUST NOT appear in plaintext
    assert "pass123" not in xml_str
    # The value must look like a base64-encoded SHA-1 digest (28 chars)
    pw_el = sec.find(f".//{{{WSSE}}}Password")
    assert pw_el is not None
    digest_text = pw_el.text or ""
    decoded = base64.b64decode(digest_text)
    assert len(decoded) == 20, "SHA-1 digest must be 20 bytes"


def test_username_token_digest_hash_formula() -> None:
    """Verify the PasswordDigest formula: Base64(SHA-1(nonce+created+password))."""
    import hashlib

    cfg = WsSecurityConfig(
        type="UsernameToken",
        username="u",
        password="pw",
        password_type="PasswordDigest",
        add_nonce=True,
        add_created=True,
        add_timestamp=False,
    )
    sec = build_security_header(cfg)
    # Extract nonce, created, and digest from the element tree
    nonce_el = sec.find(f".//{{{WSSE}}}Nonce")
    created_el = sec.find(f".//{{{WSU}}}Created")
    password_el = sec.find(f".//{{{WSSE}}}Password")
    assert nonce_el is not None and created_el is not None and password_el is not None

    nonce_bytes = base64.b64decode(nonce_el.text or "")
    created_str = (created_el.text or "").encode("utf-8")
    raw = nonce_bytes + created_str + b"pw"
    expected = base64.b64encode(hashlib.sha1(raw).digest()).decode()  # noqa: S324
    assert password_el.text == expected


def test_username_token_no_nonce_or_created() -> None:
    cfg = WsSecurityConfig(
        type="UsernameToken",
        username="u",
        password="p",
        password_type="PasswordText",
        add_nonce=False,
        add_created=False,
        add_timestamp=False,
    )
    sec = build_security_header(cfg)
    xml_str = ET.tostring(sec, encoding="unicode")
    assert "Nonce" not in xml_str
    assert "Created" not in xml_str


def test_username_token_with_timestamp() -> None:
    cfg = WsSecurityConfig(
        type="UsernameToken",
        username="u",
        password="p",
        password_type="PasswordText",
        add_timestamp=True,
        ttl_seconds=120,
    )
    sec = build_security_header(cfg)
    xml_str = ET.tostring(sec, encoding="unicode")
    assert "Timestamp" in xml_str
    assert "Expires" in xml_str


# ---------------------------------------------------------------------------
# Timestamp tests
# ---------------------------------------------------------------------------


def test_timestamp_element_has_created_and_expires() -> None:
    cfg = WsSecurityConfig(type="Timestamp", ttl_seconds=600)
    sec = build_security_header(cfg)
    xml_str = ET.tostring(sec, encoding="unicode")
    assert "Created" in xml_str
    assert "Expires" in xml_str


def test_timestamp_ttl_respected() -> None:
    """Expires must be ~ttl_seconds after Created."""
    from datetime import datetime, timezone

    cfg = WsSecurityConfig(type="Timestamp", ttl_seconds=300)
    sec = build_security_header(cfg)
    created_el = sec.find(f".//{{{WSU}}}Created")
    expires_el = sec.find(f".//{{{WSU}}}Expires")
    assert created_el is not None and expires_el is not None

    def _parse(s: str) -> datetime:
        return datetime.strptime(s, "%Y-%m-%dT%H:%M:%S.%fZ").replace(
            tzinfo=timezone.utc
        )

    delta = _parse(expires_el.text or "") - _parse(created_el.text or "")
    assert abs(delta.total_seconds() - 300) < 2


# ---------------------------------------------------------------------------
# BinarySecurityToken tests
# ---------------------------------------------------------------------------


def test_binary_security_token_embeds_cert() -> None:
    cert_b64 = base64.b64encode(b"fake-cert-data").decode()
    cfg = WsSecurityConfig(
        type="BinarySecurityToken",
        certificate_base64=cert_b64,
        add_timestamp=False,
    )
    sec = build_security_header(cfg)
    xml_str = ET.tostring(sec, encoding="unicode")
    assert cert_b64 in xml_str
    assert "X509v3" in xml_str


# ---------------------------------------------------------------------------
# Envelope injection tests
# ---------------------------------------------------------------------------


def test_inject_into_existing_header() -> None:
    cfg = WsSecurityConfig(type="Timestamp", ttl_seconds=60)
    result = inject_security(SAMPLE_ENVELOPE, cfg)
    root = ET.fromstring(result)
    header = root.find(f"{{{SOAP}}}Header")
    assert header is not None
    sec = header.find(f"{{{WSSE}}}Security")
    assert sec is not None


def test_inject_creates_header_if_missing() -> None:
    cfg = WsSecurityConfig(type="Timestamp", ttl_seconds=60)
    result = inject_security(ENVELOPE_NO_HEADER, cfg)
    root = ET.fromstring(result)
    header = root.find(f"{{{SOAP}}}Header")
    assert header is not None
    sec = header.find(f"{{{WSSE}}}Security")
    assert sec is not None


def test_inject_username_token_has_both_timestamp_and_token() -> None:
    cfg = WsSecurityConfig(
        type="UsernameToken",
        username="user1",
        password="pw",
        password_type="PasswordText",
        add_timestamp=True,
    )
    result = inject_security(SAMPLE_ENVELOPE, cfg)
    root = ET.fromstring(result)
    sec = root.find(f".//{{{WSSE}}}Security")
    assert sec is not None
    assert sec.find(f"{{{WSU}}}Timestamp") is not None
    assert sec.find(f"{{{WSSE}}}UsernameToken") is not None


# ---------------------------------------------------------------------------
# Path traversal guard tests
# ---------------------------------------------------------------------------


def test_path_traversal_blocked_absolute() -> None:
    with pytest.raises(ValueError, match="outside the allowed"):
        _safe_resolve_path("/etc/passwd")


def test_path_traversal_blocked_system_dir() -> None:
    # /var/log is outside of home + tmp — should be blocked.
    # Use a path that resolves to a known system dir not in the whitelist.
    with pytest.raises(ValueError, match="outside the allowed"):
        _safe_resolve_path("/var/log/system.log")


def test_path_traversal_tmp_allowed(tmp_path: Path) -> None:
    # /tmp subdirectory should be allowed
    p = tmp_path / "test.key"
    p.write_bytes(b"data")
    resolved = _safe_resolve_path(str(p))
    assert resolved == p.resolve()


def test_path_traversal_home_allowed() -> None:
    # Home directory should be allowed
    home = Path.home() / ".ssh" / "id_rsa"
    # Don't need the file to exist for path validation
    resolved = _safe_resolve_path(str(home))
    assert resolved == home.resolve()


# ---------------------------------------------------------------------------
# WsSecurityConfig validator tests
# ---------------------------------------------------------------------------


def test_config_rejects_path_outside_allowed() -> None:
    with pytest.raises(ValueError, match="outside the allowed"):
        WsSecurityConfig(
            type="Signature",
            key_file_path="/etc/shadow",
            cert_file_path="/etc/ssl/certs/ca-certificates.crt",
        )


# ---------------------------------------------------------------------------
# build_zeep_wsse_plugin tests
# ---------------------------------------------------------------------------


def test_zeep_plugin_username_token() -> None:
    cfg = WsSecurityConfig(
        type="UsernameToken",
        username="user",
        password="pass",
        password_type="PasswordText",
    )
    plugin = build_zeep_wsse_plugin(cfg)
    # Should be a zeep UsernameToken
    from zeep.wsse import UsernameToken

    assert isinstance(plugin, UsernameToken)


def test_zeep_plugin_username_token_digest() -> None:
    cfg = WsSecurityConfig(
        type="UsernameToken",
        username="user",
        password="pass",
        password_type="PasswordDigest",
    )
    plugin = build_zeep_wsse_plugin(cfg)
    from zeep.wsse import UsernameToken

    assert isinstance(plugin, UsernameToken)
    assert plugin.use_digest is True


def test_zeep_plugin_timestamp() -> None:
    cfg = WsSecurityConfig(type="Timestamp", ttl_seconds=120)
    plugin = build_zeep_wsse_plugin(cfg)
    assert isinstance(plugin, _TimestampPlugin)


def test_zeep_plugin_memory_signature(key_pem: str, cert_pem: str) -> None:
    cfg = WsSecurityConfig(
        type="MemorySignature",
        key_pem=key_pem,
        cert_pem=cert_pem,
        signature_algorithm="RSA-SHA256",
    )
    plugin = build_zeep_wsse_plugin(cfg)
    from zeep.wsse.signature import MemorySignature

    assert isinstance(plugin, MemorySignature)


def test_zeep_plugin_memory_signature_sha1(key_pem: str, cert_pem: str) -> None:
    cfg = WsSecurityConfig(
        type="MemorySignature",
        key_pem=key_pem,
        cert_pem=cert_pem,
        signature_algorithm="RSA-SHA1",
    )
    plugin = build_zeep_wsse_plugin(cfg)
    from zeep.wsse.signature import MemorySignature

    assert isinstance(plugin, MemorySignature)
    import xmlsec

    assert plugin.signature_method == xmlsec.constants.TransformRsaSha1


def test_zeep_plugin_signature_from_files(tmp_path: Path) -> None:
    import shutil

    key_dest = tmp_path / "test.key"
    cert_dest = tmp_path / "test.crt"
    shutil.copy(KEY_FILE, key_dest)
    shutil.copy(CERT_FILE, cert_dest)

    cfg = WsSecurityConfig(
        type="Signature",
        key_file_path=str(key_dest),
        cert_file_path=str(cert_dest),
        signature_algorithm="RSA-SHA256",
    )
    plugin = build_zeep_wsse_plugin(cfg)
    from zeep.wsse.signature import MemorySignature

    assert isinstance(plugin, MemorySignature)


def test_zeep_plugin_signature_missing_files_raises() -> None:
    cfg = WsSecurityConfig(type="Signature")
    with pytest.raises(ValueError, match="key_file_path"):
        build_zeep_wsse_plugin(cfg)


def test_zeep_plugin_memory_signature_missing_pem_raises() -> None:
    cfg = WsSecurityConfig(type="MemorySignature")
    with pytest.raises(ValueError, match="key_pem"):
        build_zeep_wsse_plugin(cfg)


def test_zeep_plugin_invalid_algorithm_raises(key_pem: str, cert_pem: str) -> None:
    cfg = WsSecurityConfig(
        type="MemorySignature",
        key_pem=key_pem,
        cert_pem=cert_pem,
        signature_algorithm="RSA-SHA256",  # valid to pass pydantic
    )
    # Manually override to test _sig_algorithm guard
    from theridion_sidecar.api.ws_security import _sig_algorithm

    with pytest.raises(ValueError, match="Unsupported"):
        _sig_algorithm("RSA-MD5")


# ---------------------------------------------------------------------------
# XML Signature algorithm constants test
# ---------------------------------------------------------------------------


def test_rsa_sha256_constant() -> None:
    import xmlsec

    from theridion_sidecar.api.ws_security import _sig_algorithm

    assert _sig_algorithm("RSA-SHA256") == xmlsec.constants.TransformRsaSha256


def test_rsa_sha1_constant() -> None:
    import xmlsec

    from theridion_sidecar.api.ws_security import _sig_algorithm

    assert _sig_algorithm("RSA-SHA1") == xmlsec.constants.TransformRsaSha1


# ---------------------------------------------------------------------------
# _TimestampPlugin lxml test
# ---------------------------------------------------------------------------


def test_timestamp_plugin_apply_produces_timestamp_element() -> None:
    """_TimestampPlugin.apply should insert a wsu:Timestamp into the header."""
    from lxml import etree

    SOAP_NS = "http://schemas.xmlsoap.org/soap/envelope/"
    WSU_NS = WSU
    WSSE_NS = WSSE

    envelope = etree.fromstring(
        b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">'
        b"<soap:Header/>"
        b"<soap:Body><Ping/></soap:Body>"
        b"</soap:Envelope>"
    )
    plugin = _TimestampPlugin(ttl_seconds=60)
    result_env, _ = plugin.apply(envelope, {})
    # Find the Security element
    header = result_env.find(f"{{{SOAP_NS}}}Header")
    assert header is not None
    sec = header.find(f"{{{WSSE_NS}}}Security")
    assert sec is not None
    ts = sec.find(f"{{{WSU_NS}}}Timestamp")
    assert ts is not None
    assert ts.find(f"{{{WSU_NS}}}Created") is not None
    assert ts.find(f"{{{WSU_NS}}}Expires") is not None


# ---------------------------------------------------------------------------
# HTTP endpoint tests
# ---------------------------------------------------------------------------


def test_ws_security_execute_malformed_xml_returns_422(client: TestClient) -> None:
    resp = client.post(
        "/api/soap/ws-security/execute",
        json={
            "url": "http://localhost:9999",
            "envelope_xml": "THIS IS NOT XML",
            "security": {"type": "Timestamp"},
        },
    )
    assert resp.status_code == 422


def test_soap_execute_accepts_wsse_username_token_field(client: TestClient) -> None:
    """Schema validation: /api/soap/execute should accept a wsse UsernameToken."""
    # We use the fixture WSDL (file://) which will fail transport, but
    # the important thing is that the wsse field is accepted by the schema
    # and a wsse_plugin is built without error.
    FIXTURE = Path(__file__).parent / "fixtures" / "calculator.wsdl"
    resp = client.post(
        "/api/soap/execute",
        json={
            "wsdl_url": f"file://{FIXTURE.resolve()}",
            "operation": "Add",
            "args": {"a": 1, "b": 2},
            "wsse": {
                "type": "UsernameToken",
                "username": "user",
                "password": "pass",
                "password_type": "PasswordText",
            },
        },
    )
    # Transport will fail (example.com), but we should NOT get a 400/422
    # for WS-Security configuration — shape must be valid.
    assert resp.status_code == 200
    body = resp.json()
    assert "ok" in body


def test_soap_execute_invalid_wsse_type_returns_422(client: TestClient) -> None:
    FIXTURE = Path(__file__).parent / "fixtures" / "calculator.wsdl"
    resp = client.post(
        "/api/soap/execute",
        json={
            "wsdl_url": f"file://{FIXTURE.resolve()}",
            "operation": "Add",
            "args": {},
            "wsse": {"type": "InvalidType"},
        },
    )
    assert resp.status_code == 422


def test_soap_execute_signature_missing_files_returns_400(client: TestClient) -> None:
    """Missing key/cert files for Signature mode → 400."""
    FIXTURE = Path(__file__).parent / "fixtures" / "calculator.wsdl"
    resp = client.post(
        "/api/soap/execute",
        json={
            "wsdl_url": f"file://{FIXTURE.resolve()}",
            "operation": "Add",
            "args": {},
            "wsse": {
                "type": "Signature",
                "key_file_path": None,
                "cert_file_path": None,
            },
        },
    )
    assert resp.status_code == 400
    assert "WS-Security" in resp.json()["detail"]
