// Generated by /Users/tm/workspaces/bin/sync-security.py - DO NOT EDIT MANUALLY.
// app/ai.txt/route.ts
// Profile: internal-only
//
// ai.txt RFC (https://site.spawning.ai/spawning-ai-txt) - explicitni opt-out z AI training.
// Distinct od robots.txt - target jen AI crawlers, ne search engines.

export const dynamic = "force-static";

export function GET(): Response {
  const body = `# ai.txt - https://theridion.qawave.ai
# Spec: https://site.spawning.ai/spawning-ai-txt
#
# Tento web je proprietary. Zadny obsah neni licencovany pro
# trenink AI modelu nebo derivative AI generation.

User-Agent: *
Disallow: /

# Specificky pro znamé AI crawlery (redundance, ale explicitni):
User-Agent: GPTBot
Disallow: /

User-Agent: ChatGPT-User
Disallow: /

User-Agent: ClaudeBot
Disallow: /

User-Agent: Claude-Web
Disallow: /

User-Agent: anthropic-ai
Disallow: /

User-Agent: CCBot
Disallow: /

User-Agent: Google-Extended
Disallow: /

User-Agent: PerplexityBot
Disallow: /

User-Agent: Bytespider
Disallow: /

User-Agent: cohere-ai
Disallow: /
`;

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
}
