// Generated by /Users/tm/workspaces/bin/sync-security.py - DO NOT EDIT MANUALLY.
// app/x-honeypot-internal/route.ts
//
// Honeypot endpoint - listed v robots.txt jako Disallow, takze legit user/bot
// ho navstivit nemel. Kazda navsteva = pravdepodobne scraper ignorujici robots.
// Pri kazdem hitu logujeme Sentry event s tagy a vracime 410 Gone.

import { tagSecurityEvent } from "@/lib/security/sentry-tags";

export const dynamic = "force-dynamic";

export async function GET(request: Request): Promise<Response> {
  const ip =
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    request.headers.get("x-real-ip") ??
    "unknown";
  const userAgent = request.headers.get("user-agent") ?? "unknown";

  await tagSecurityEvent("honeypot.hit", {
    ip,
    userAgent,
    referer: request.headers.get("referer") ?? "none",
    path: new URL(request.url).pathname,
  });

  return new Response("Gone\n", {
    status: 410,
    headers: {
      "Content-Type": "text/plain",
      "X-Robots-Tag": "noindex, noai, noimageai",
      "Cache-Control": "no-store",
    },
  });
}
