// Generated by /Users/tm/workspaces/bin/sync-security.py - DO NOT EDIT MANUALLY.
// Source: /Users/tm/workspaces/teams/dev-team/security/templates/proxy.ts
// Profile: internal-only
//
// Next.js 16+ proxy.ts (nahrazuje middleware.ts).
// Aplikuje security headers + X-Robots-Tag per cesta.
// Nemodifikuje cookies/session - jen response headers.

import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

const SECURITY_HEADERS: Record<string, string> = {
  "X-Frame-Options": "DENY",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Cross-Origin-Opener-Policy": "same-origin",
  "Cross-Origin-Resource-Policy": "same-site",
  "Permissions-Policy":
    "camera=(), microphone=(), geolocation=(), interest-cohort=(), browsing-topics=()",
};

// Cesty, kde NEchceme AI crawlery (aplikuje X-Robots-Tag: noai, noimageai).
const AI_BLOCKED_PATHS: RegExp[] = [
  /^\/(dashboard|portal|admin|app|api)(\/|$)/i,
  /^\/(faktury|pokladna|klient|interni)(\/|$)/i,
];

export function proxy(request: NextRequest): NextResponse {
  const response = NextResponse.next();
  const url = request.nextUrl;

  for (const [k, v] of Object.entries(SECURITY_HEADERS)) {
    response.headers.set(k, v);
  }

  const isAiBlocked = AI_BLOCKED_PATHS.some((re) => re.test(url.pathname));
  if (isAiBlocked) {
    response.headers.set("X-Robots-Tag", "noai, noimageai, noindex");
  } else {
    // Public/marketing - dovol indexovani, ale ne AI training.
    response.headers.set("X-Robots-Tag", "noai, noimageai");
  }

  return response;
}

export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp|avif|ico|woff2?|ttf|otf|eot)$).*)",
  ],
};
