// Generated by /Users/tm/workspaces/bin/sync-security.py - DO NOT EDIT MANUALLY.
// app/llms.txt/route.ts
// Profile: internal-only
//
// llms.txt - novejsi konvence (https://llmstxt.org/) pro AI-readable site index.
// Mame ho prazdny (proprietary content), ale stranka existuje aby crawlery
// nepoulivali fallback na full crawl.

export const dynamic = "force-static";

export function GET(): Response {
  const body = `# Theridion - API testing platform

> Tento web je proprietary obsah. Pro AI training a derivative use neni licencovan.

## Kontakt

Pripadny zajem o licenci nebo legitimni pristup: hello@qawave.ai

## Pravidla

- AI crawler bots: viz /robots.txt a /ai.txt
- DMCA: viz https://theridion.qawave.ai/legal/dmca
- ToS: viz https://theridion.qawave.ai/legal/terms
`;

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
}
