// Generated by /Users/tm/workspaces/bin/sync-security.py - DO NOT EDIT MANUALLY.
// src/lib/security/arcjet.ts
//
// Arcjet wrapper - bot detection + rate limiting + shield.
// Mode: DRY_RUN default - jen loguje rozhodnuti, nic neblokuje.
// Pro production zapnout LIVE pres env ARCJET_MODE=LIVE.
//
// Install: `npm install @arcjet/next`
// Env: ARCJET_KEY (z https://app.arcjet.com)

import arcjet, {
  shield,
  detectBot,
  tokenBucket,
  type ArcjetMode,
} from "@arcjet/next";

const mode: ArcjetMode =
  (process.env.ARCJET_MODE as ArcjetMode) === "LIVE" ? "LIVE" : "DRY_RUN";

export const aj = arcjet({
  key: process.env.ARCJET_KEY ?? "",
  rules: [
    // OWASP-style shield - SQL injection, XSS, traversal heuristics.
    shield({ mode }),

    // Bot detection - povolime search engines a monitoring, ostatni challenge.
    detectBot({
      mode,
      allow: [
        "CATEGORY:SEARCH_ENGINE",
        "CATEGORY:MONITOR",
        "CATEGORY:PREVIEW",
      ],
    }),

    // Token bucket - 30 req capacity, refill 10/min.
    tokenBucket({
      mode,
      refillRate: 10,
      interval: 60,
      capacity: 30,
    }),
  ],
});

// Strikter limit pro AI / expensive endpoints.
export const ajStrict = arcjet({
  key: process.env.ARCJET_KEY ?? "",
  rules: [
    shield({ mode }),
    detectBot({
      mode,
      allow: ["CATEGORY:MONITOR"],
    }),
    tokenBucket({
      mode,
      refillRate: 3,
      interval: 60,
      capacity: 5,
    }),
  ],
});
