// Generated by /Users/tm/workspaces/bin/sync-security.py - DO NOT EDIT MANUALLY.
// src/lib/security/sentry-tags.ts
//
// Helper pro tagovani security eventu do Sentry.
// Funguje aj bez Sentry SDK - tise loguje na server console (no-op fallback).

type SecurityEventKind =
  | "honeypot.hit"
  | "rate_limited"
  | "bot.detected"
  | "csp_violation"
  | "auth.brute_force"
  | "scrape.suspected";

interface SecurityEventMeta {
  ip?: string;
  userAgent?: string;
  referer?: string;
  path?: string;
  reason?: string;
  [key: string]: string | undefined;
}

export async function tagSecurityEvent(
  kind: SecurityEventKind,
  meta: SecurityEventMeta,
): Promise<void> {
  // Pokus o Sentry SDK (kdyz je instalovany).
  try {
    const Sentry = await import("@sentry/nextjs").catch(() => null);
    if (Sentry && typeof Sentry.captureMessage === "function") {
      Sentry.captureMessage(`security:${kind}`, {
        level: "warning",
        tags: {
          security_event: kind,
          ip: meta.ip ?? "unknown",
          path: meta.path ?? "unknown",
        },
        extra: meta,
      });
      return;
    }
  } catch {
    // Pad-through - Sentry neni instalovany nebo verze nesedi.
  }

  // Fallback - server console log (zachyti to Vercel Functions log).
  // eslint-disable-next-line no-console
  console.warn(
    JSON.stringify({
      kind: `security:${kind}`,
      ts: new Date().toISOString(),
      ...meta,
    }),
  );
}
